GR__ZINDEX__LOWEST = 0
GR__ZINDEX__LOW = 1000
GR__ZINDEX__MEDIUM = 2000
GR__ZINDEX__HIGH = 3000
GR__ZINDEX__HIGHEST = 4000

GR__CARD__WIDTH_RATIO = 2.5
GR__CARD__HEIGHT_RATIO = 3.5

GR__SCREEN__WIDTH = 400
GR__SCREEN__HEIGHT = 240
GR__SCREEN__X_CENTER = GR__SCREEN__WIDTH / 2
GR__SCREEN__Y_CENTER = GR__SCREEN__HEIGHT / 2

GR__CARD__WIDTH = GR__SCREEN__WIDTH / 4
GR__CARD__HEIGHT = (GR__CARD__WIDTH * GR__CARD__HEIGHT_RATIO) / GR__CARD__WIDTH_RATIO
GR__CARD__SYMBOL__HEIGHT = Card.getSymbolHeight(GR__CARD__WIDTH)
GR__CARD__SYMBOL__PADDING = Card.getSymbolPadding(GR__CARD__WIDTH)
GR__CARD__Y_OPPONENT = -(GR__CARD__HEIGHT / 2) + (GR__CARD__HEIGHT / 5)
GR__CARD__Y_PLAYER = (GR__SCREEN__HEIGHT + GR__CARD__HEIGHT / 2) - (GR__CARD__SYMBOL__HEIGHT + GR__CARD__SYMBOL__PADDING * 2)

GR__COLUMN__BORDER_THICKNESS = 2
GR__COLUMN__PADDING = 5
GR__COLUMN__WIDTH = (GR__SCREEN__WIDTH - (GR__COLUMN__PADDING * (BOARD_COLUMNS_COUNT + 1))) / BOARD_COLUMNS_COUNT
GR__COLUMN__HEIGHT_BOTH = GR__SCREEN__HEIGHT - (GR__CARD__Y_OPPONENT + (GR__CARD__HEIGHT / 2)) - (GR__SCREEN__HEIGHT - (GR__CARD__Y_PLAYER - (GR__CARD__HEIGHT / 2))) - (GR__COLUMN__PADDING * 2)
GR__COLUMN__HEIGHT_OPPONENT = GR__SCREEN__HEIGHT - (GR__CARD__Y_OPPONENT + (GR__CARD__HEIGHT / 2)) - (GR__COLUMN__PADDING * 2)
GR__COLUMN__BLOCK__HEIGHT = GR__COLUMN__HEIGHT_BOTH / ((STACK_MAXIMUM_CARD_COUNT * 2) + 1)
GR__COLUMN__WIDTH_AND_PADDING = GR__COLUMN__WIDTH + GR__COLUMN__PADDING